[package]
name = "vt100-ctt"
version = "0.16.0"
authors = [
    "Chris Titus <contact@christitus.com>",
    "Jesse Luehrs <doy@tozt.net>",
]
edition = "2021"

description = "Library for parsing terminal data - up-to-date version"
homepage = "https://github.com/ChrisTitusTech/vt100-rust"
repository = "https://github.com/ChrisTitusTech/vt100-rust"
readme = "README.md"
keywords = ["terminal", "vt100"]
categories = ["command-line-interface", "encoding"]
license = "MIT"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
itoa = "1.0.11"
log = "0.4.22"
unicode-width = "0.2.0"
vte = "0.13.0"
ratatui = { version = "0.29.0", default-features = false, optional = true }
tui-term = { version = "0.2.0", default-features = false, optional = true }

[features]
default = ["tui-term"]
tui-term = ["dep:tui-term", "dep:ratatui"]

[dev-dependencies]
nix = { version = "0.29.0", features = ["term"] }
quickcheck = "1.0"
rand = "0.8"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
terminal_size = "0.4.0"
vte = "0.13.0"
