[package]
name = "vt100"
version = "0.1.2"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

description = "Library for parsing terminal data"
homepage = "https://github.com/doy/vt100-rust"
repository = "https://github.com/doy/vt100-rust"
readme = "README.md"
keywords = ["terminal", "vt100"]
license = "MIT"
